version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finatext
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate:v4.15.2
    depends_on:
      mysql:
        condition: service_healthy
    command:
      [
        "-path", "/migrations",
        "-database", "mysql://user:password@tcp(mysql:3306)/finatext?multiStatements=true",
        "up"
      ]
    volumes:
      - ./migrations:/migrations

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app

volumes:
  mysql-data:
